### ISSUE TITLE
downloading GACOS data

### ISSUE THREAD

**Issue by mirzaees** [SubhadipDatta/GInSARCorW#1]
Hello,
I cannot open the following link,
http://ceg-research.ncl.ac.uk/v2/gacos/
Could you please help me to access the data?

**Comment by SubhadipDatta** [comment]
According to the tweet from GACOS_Newcastle dated Sep 12, Their server is currently offline due to a cyber attack. Hope for a quick fix.[@GACOS_Newcastle](https://twitter.com/GACOS_Newcastle)
